### ISSUE TITLE
position relative i absolute no funciona

### ISSUE THREAD

**Issue by aagudobruno** [aagudobruno/exercicis_DWIC#3]
https://github.com/aagudobruno/exercicis_DWIC/blob/1005fc6251e7c392f6e0c3e8eb4a1ea2a94c9d19/e01.1/e01.1_CSS%20Basic.css#L153

aquí no entenc perquè no funciona el position absolute.

**Comment by classicoman2** [comment]
![image](https://user-images.githubusercontent.com/43608231/95358397-4d1b1000-08c9-11eb-8f82-78b9209a8f47.png)

alerta als id !

**Comment by aagudobruno** [comment]
ostres, gràcies
